FROM python:3

# set working directory
WORKDIR /usr/src/app

# copy project file
COPY requirements.txt .

# install dependencies
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

# copy all project
COPY . .

# run test
CMD [ "python", "./test.py" ]